### ISSUE TITLE
SDK docs

### ISSUE THREAD

**Issue by JrPribs** [Backendless/Console-SDK#30]
Opening an issue as I figure this is the easiest way to get some quick answers. 
Does this SDK support both 3.x and 4.x endpoints?
Is there any usage information on this SDK? 
If there are no usage docs in progress I would be glad to help get that going if someone can provide a usage example.

**Comment by markpiller** [comment]
The SDK works only with the 4.0 version of the product. I will let the developers help with an example showing the usage.

**Comment by JrPribs** [comment]
@markpiller oh all good, I need it for 3.x :(  I will keep it in mind when we get all migrated to 4 in the hopefully near future though, thanks!
